### ISSUE TITLE
How it work?

### ISSUE THREAD

**Issue by MateuszCOMP** [ReHamster/Alcatraz#2]
Hello 
I Have question how its made
Alcatraz using multiplayer build in game and only swapping ubisoft server to own 
OR 
It's stand alone multiplayer, something like sa-mp (gta san andreas multiplayer)?

**Comment by SoapyMan** [comment]
Alcatraz re-implements same online functionality. If Ubisoft decides to close DSF servers, Alcatraz basically backs it up.
