### ISSUE TITLE
Game crashes upon start.

### ISSUE THREAD

**Issue by edoo1** [ReHamster/Alcatraz#33]
I have installed 1.5 Launcher first and after that installed 1.6 and the game doesn't start. Right at the beginning I see an Error that says "We got an fatal error. Minidump will be saved near .exe
I also included the dump in this post so I hope someone can help me out with this.

![Screenshot 2023-11-27 160322](https://github.com/ReHamster/Alcatraz/assets/39381258/88b9c0cf-5cd5-4485-970b-
[Driver_20231127_150610.dmp](https://github.com/ReHamster/Alcatraz/files/13476723/Driver_20231127_150610.dmp)
9e846b459817)

**Comment by edoo1** [comment]
I'm not sure everything got uploaded properly so I also want to include a Mediafire Link in case the dump and the screenshot cannot be viewed: https://www.mediafire.com/file/fww8dreagizivwf/dump_ss.zip/file

**Comment by SoapyMan** [comment]
You have ASUS GPU Tweak III OSD loaded and it possibly crashes the DirectX9 renderer. Try turning it off

**Comment by edoo1** [comment]
That's a really strange issue. I played through this game multiple times and had GPU Tweak on and it worked just fine. Now I shut it off with the Alcatraz Launcher installed and it just worked. I never thought that something like this would be the issue but nonetheless I really appreciate your help and quick response time, thank you!
