### ISSUE TITLE
Joining private sessions when joining public sessions?

### ISSUE THREAD

**Issue by thisisauser9** [ReHamster/Alcatraz#9]
I joined a public session and I found a match, however after winning (Like usual) I realised I didn't get an XP and I then realised that there was no qualifying, the people seemed to have set up a private match, made it tag only and disabled qualifying which can only be done in a private match idk if this is a known bug but I haven't see anybody report it so kek

**Comment by SoapyMan** [comment]
Yeah, definitely unknown bug. Thanks for report!

**Comment by SoapyMan** [comment]
Fixed this one.
